Fix: crash_test: do not use firewalld to block port
ClusterLabs/crmsh pull request #1024
Opened 2022-09-01 06:28 UTC by nicholasyang2022

Removing ports from firewalld zone will not break established connections.

2022-09-06 06:20 UTC, zzhou1 requested changes
Great, I like the idea to delete do_block_firewalld() and it does simplify code. The goal of the use case to simulate an isolated cluster node and it is good enough to let do_block_iptables() do the job on-the-fly.

Question, did you verify 5-node for diskless sbd use case, btw?

Minor comments, 
- It is useful tracking reference to add bsc#1192467 in the commit log. 
- I prefer the title to be more use case oriented, something like
  "Fix: crash_test: do not use firewalld to isolate the cluster node"

2022-09-06 10:55 UTC, nicholasyang2022 commented
> Question, did you verify 5-node for diskless sbd use case, btw?

I verified it today. The isolated node self fences after SBD_TIMEOUT and remaining nodes form new membership after stonish timeout.

2022-09-13 07:43 UTC, zzhou1 approved these changes

2022-09-14 01:22 UTC, liangxin1300 approved these changes
LGTM
Thanks!

2022-09-14 01:22 UTC, merged