Fix: utils: Add 'sudo' only when there is a sudoer(bsc#1215549)
ClusterLabs/crmsh pull request #1253
Opened 2023-09-25 06:36 UTC by liangxin1300

backport #1247

2023-11-24 08:20 UTC, nicholasyang2022 approved these changes

2023-11-24 08:23 UTC, nicholasyang2022 requested changes
It is preferred to avoid using split to parse cmdline arguments to avoid shell injection.

2023-11-26 14:16 UTC, liangxin1300 commented
> It is preferred to avoid using split to parse cmdline arguments to avoid shell injection.

Changed on all 3 PRs

Thanks for pointing this!

2023-11-29 07:17 UTC, nicholasyang2022 commented
This change does not work. If whitespace characters exist in `host`, `shlex.split` will still split it. To avoid shell injection, arguments should not be composed into a command line without validation. For this case, it is preferred to operate on the argument array instead of command line string.

2023-11-29 14:00 UTC, liangxin1300 commented
> This change does not work. If whitespace characters exist in `host`, `shlex.split` will still split it. To avoid shell injection, arguments should not be composed into a command line without validation. For this case, it is preferred to operate on the argument array instead of command line string.

Changed
Please take a look.
Thanks!

2023-11-30 09:01 UTC, nicholasyang2022 approved these changes
~~{"ssh", "true"} is not the same as {"ssh", "", "true"}. However, it seems that ssh ignore an empty arg and this does not cause any problem.~~

2023-11-30 09:05 UTC, nicholasyang2022 commented on crmsh/utils.py
> +        args.extend(['-o', 'BatchMode=yes', host, sudo_str, 'true'])
1. When passing arguments as array of strings, space is not needed. Space is the separator of arguments in shell. See `init main(int argc, char **argv)` and `execve(1)`.
2. An empty argument is not the same as non-existing argument. `argv = {"true"}` and  `argv = {"", "true"}` is not the same.

```suggestion
        if userdir.get_sudoer():
            args.extend(['-o', 'BatchMode=yes', host, 'sudo', 'true'])
        else:
            args.extend(['-o', 'BatchMode=yes', host, 'true'])
```

2023-12-05 04:23 UTC, nicholasyang2022 approved these changes

2023-12-05 04:47 UTC, merged