[crmsh] Dev: pre-migration: implement pre-migration checks for corosync 3 (jsc#PED-8252)
ClusterLabs/crmsh pull request #1629
Opened 2024-12-13 07:35 UTC by nicholasyang2022

This pull request implements pre-migration checks for corosync 3. These checks are expected to run before upgrading corosync package to 3.x.

These checks ensure all the cluster nodes runs the latest version of corosync 2.x, and report further actions need to take after upgrading the corosync package.

---

# Use Cases

## `crm cluster health sles16`

```
> sudo crm cluster health sles16

------ ha-1-2 ------
[INFO] Corosync transport "udpu" will be deprecated in corosync 3.
       After migrating to SLES 16, run "crm health sles16 --fix" to migrate it to transport "knet".
[PASS]
------ localhost ------
[INFO] Checking dependency version...
[INFO] Checking service status...
[INFO] Corosync transport "udpu" will be deprecated in corosync 3.
       After migrating to SLES 16, run "crm health sles16 --fix" to migrate it to transport "knet".
[PASS]
```

## `crm cluster health sles16 --fix`

```
> sudo crm cluster health sles16 --fix
ERROR: "--fix" is only available in SLES 16.
```

2025-01-01 14:01 UTC, liangxin1300 commented on crmsh/migration-supported-resource-agents.txt
> +stonith:fence_zvm
How has the above data been generated?
Can we automatically do that based on the local installed resource-agents and fence-agents-* rpm?

2025-01-01 23:03 UTC, nicholasyang2022 commented on crmsh/migration-supported-resource-agents.txt
> +stonith:fence_zvm
> How has the above data been generated?

Extracted the file list from resource-agents/fence-agents.

> Can we automatically do that based on the locally installed resource-agents and fence-agents-* rpm?

No, because we need to know what is supported by SLES 16 instead of SLES 15 SP6.

2025-01-03 05:41 UTC, liangxin1300 commented
Suggestion: add completer for `crm cluster health`, now `hawk2` can be completed, so do `sles16`

2025-01-03 06:27 UTC, liangxin1300 commented
Suggestion:
#### 6. How about there are Failed Resource Actions?
For some reason, some RA failed. For now, `crm cluster health sles16` seems quiet for such an error.
I think we should hint the user to address that failed RA, then do the migration job

2025-01-03 06:43 UTC, liangxin1300 commented on crmsh/migration.py
> +        'After migrating to SLES 16, run "crm health sles16 --fix" to migrate it to transport "knet".',
Should be `crm cluster health sles16 --fix`

2025-01-03 06:43 UTC, liangxin1300 commented on crmsh/migration.py
> +            'After migrating to SLES 16, run "crm health sles16 --fix" to migrate it to knet multilink.',
Should be `crm cluster health sles16 --fix`

2025-01-06 05:22 UTC, nicholasyang2022 commented
> 1. Add completer for crm cluster health, now hawk2 can be completed, so do sles16

:heavy_check_mark:

> 2. Add success info
> 3. Add failure error

:heavy_check_mark: in fd27f8ba8b9012b73793c1321225c09c4c6dec0

> I prefer this [INFO] one, since [PASS] is not the log level

> 4. Add above output into /var/log/crmsh/crmsh.log log file, too

No. These are not logs. They are user interface.

> And, change [FAIL] to [ERROR]

No. This breaks text alignment in the UI.

> 5. Keep the color of node line consistency

:heavy_check_mark: in 9f8e35e5117aefb36576fd4be640d9780ceb7673

> 6. How about there are Failed Resource Actions?

This looks more like a general health check instead of a migration check. Let's discuss further before working the code.

2025-01-06 06:31 UTC, liangxin1300 commented
Suggestion
#### 10. Add some behave functional test cases to hit the coverage

2025-01-07 04:10 UTC, nicholasyang2022 commented
> 7. crm report collect pre-migration info

Let's keep this pull request to focus on implement pre-migration checks, and add it in a separated pull request.

> 8. Inaccurate usage?

Fixed.

> 9. Fence agents checking

Added a message specially for `stonith:external/sbd` in 6075723cc2b8f57666650a307aad194bb44a6494.

2025-01-08 08:03 UTC, liangxin1300 commented
> > 7. crm report collect pre-migration info
> 
> Let's keep this pull request to focus on implement pre-migration checks, and add it in a separated pull request.

I will create one PR about that

2025-01-13 03:35 UTC, liangxin1300 commented on crmsh/cibquery.py
> +"""utilities for parsing CIB xml"""
Maybe it's better to move these codes into xmlutil.py instead of creating a new py  file?

2025-01-13 03:35 UTC, liangxin1300 commented on crmsh/cibquery.py
> +def has_primitive_filesystem_ocfs2(cib: lxml.etree.Element) -> bool:
Considering we might use this to detect gfs2, could you please change 'ocfs2' as a parameter?

2025-01-13 03:35 UTC, liangxin1300 commented on crmsh/migration.py
> +    crm_mon = xmlutil.CrmMonXmlParser()
This is not used

2025-01-13 03:35 UTC, liangxin1300 commented on crmsh/migration-supported-resource-agents.txt
How about moving this file under `crmsh/crmsh/data`, in case there are other txt files in the future?

2025-01-13 03:35 UTC, liangxin1300 commented on crmsh/migration.py
> +def check(args: typing.Sequence[str]) -> int:
It is better to add a docstring to:
- explain what the `--json` and `--local` option are used for
- introduce this function and return code

2025-01-13 04:38 UTC, nicholasyang2022 commented on crmsh/migration.py
> +def check(args: typing.Sequence[str]) -> int:
This is quite self-explained. Adding docstrings like "migration.check: run migration checks", or "--json    output the result in json format" does not make sense. And the return code is also the common main() style return code.

2025-01-13 04:40 UTC, nicholasyang2022 commented on crmsh/migration-supported-resource-agents.txt
I prefer not to do that. I think this will need to add a python module `crmsh.data`, making our build scripts more complex.

2025-01-13 06:27 UTC, liangxin1300 commented
This usage is correct
```
# crm cluster health xxx
usage: crm cluster health [-h] [-f] {hawk2,sles16}
crm cluster health: error: argument component: invalid choice: 'xxx' (choose from 'hawk2', 'sles16')
```
But not this
```
# crm cluster health sles16 fs
usage: crm [-h] [--json [{oneline,pretty}]] [--local]
crm: error: unrecognized arguments: fs
```

2025-01-13 06:46 UTC, nicholasyang2022 commented on crmsh/cibquery.py
> +"""utilities for parsing CIB xml"""
No. xmlutil.py is too long, and its name does not reflect its content. Instead of general xml processing utilities, it is a mixed mess with shell utils, CIB specific routines, and even CLI handlers.

2025-01-13 07:06 UTC, nicholasyang2022 commented
Usages changed to

```
suse@ha-1-1:~> sudo crm cluster health foo
usage: health [-h] [-f] {hawk2,sles16}
health: error: argument component: invalid choice: 'foo' (choose from 'hawk2', 'sles16')
```

```
suse@ha-1-1:~> sudo crm cluster health sles16 foo
usage: sles16 [-h] [--json [{oneline,pretty}]] [--local]
sles16: error: unrecognized arguments: foo
```

2025-01-13 08:02 UTC, liangxin1300 commented on doc/crm.8.adoc
> +issues.
Please add note that --fix only available at SLES 16

2025-01-13 08:14 UTC, nicholasyang2022 commented on crmsh/migration.py
> +    if corosync.get_value("totem.rrp_mode") in {'active', 'passive'}:
`none` means SRP, which is supported and does not needs any actions.

2025-01-13 12:29 UTC, liangxin1300 approved these changes
Looks good to me, great work!

Thanks!

2025-01-15 10:13 UTC, zzhou1 requested changes
Great work, some feedback,

- Reporting the CIB related check result in "localhost" is misleading, since they are concepts at the cluster level when the cluster is running. 

- What to interpret the cluster is down? Since in this case, the CIB check is kind of local, the open question is should CIB check run in the remote node?

- "Good to migrate to SLES 16." on ha-1-2 is not right, while CIB check is "FAIL" at the cluster level in the summary section.

2025-01-16 09:13 UTC, zzhou1 commented
Wonderful, thanks for the great work! 
Let's merge this PR into the development branch instead of the official 4.6 branch for the timebeing.

2025-01-16 09:26 UTC, merged